import { useEffect, useMemo, useState } from 'react';
import { api, API_URL } from './api';

const icons = { home:'⌂', feed:'◈', courses:'◉', notes:'▤', people:'♙', messages:'✉', applications:'◫', admin:'◐', profile:'◎', logout:'↪', add:'+', bell:'●', search:'⌕', arrow:'→', check:'✓' };
const roleCopy = {
  student: ['Student space', 'Discover courses, connect with mentors, and manage your learning journey.'],
  teacher: ['Teacher studio', 'Share knowledge, grow your community, and guide learners forward.'],
  school: ['School command centre', 'Build your institution’s community and review incoming applications.'],
  admin: ['Admin control room', 'Keep the EduConnect community safe, trusted, and growing.'],
};

function decodeToken(token) { try { return JSON.parse(atob(token.split('.')[1].replace(/-/g, '+').replace(/_/g, '/'))); } catch { return {}; } }
function Logo() { return <div className="brand"><span className="brand-mark">e</span><span>edu<span>connect</span></span></div>; }
function Button({ children, className='', ...props }) { return <button className={`button ${className}`} {...props}>{children}</button>; }
function Toast({ message, type, onClose }) { useEffect(() => { const t = setTimeout(onClose, 4200); return () => clearTimeout(t); }, [onClose]); return <div className={`toast ${type}`}>{type === 'success' ? '✓' : '!'} <span>{message}</span><button onClick={onClose}>×</button></div>; }

function Auth({ onAuth, notify }) {
  const [mode, setMode] = useState('login'); const [busy, setBusy] = useState(false);
  const [form, setForm] = useState({ email:'', password:'', username:'', role:'student' });
  const change = e => setForm({ ...form, [e.target.name]: e.target.value });
  async function submit(e) {
    e.preventDefault(); setBusy(true);
    try {
      if (mode === 'signup') { await api('/signup', { method:'POST', body:form }); notify('Account created. You can now sign in.', 'success'); setMode('login'); }
      else { const data = await api('/login', { method:'POST', body:{email:form.email,password:form.password} }); onAuth(data.access_token); }
    } catch (err) { notify(err.message, 'error'); } finally { setBusy(false); }
  }
  return <main className="auth-page"><section className="auth-story"><Logo /><div className="hero-orb orb-one"/><div className="hero-orb orb-two"/><div className="auth-copy"><span className="eyebrow">THE EDUCATION NETWORK</span><h1>Where every<br/><em>ambition</em> finds<br/>its people.</h1><p>One considered space for students, teachers and institutions to learn, exchange and move forward together.</p><div className="member-stack"><span>AK</span><span>RS</span><span>MN</span><b>Join a growing learning community</b></div></div><small>© 2026 EduConnect. Built for brighter futures.</small></section>
  <section className="auth-panel"><div className="auth-card"><div className="mobile-logo"><Logo /></div><p className="eyebrow">WELCOME {mode === 'login' ? 'BACK' : 'TO EDUCONNECT'}</p><h2>{mode === 'login' ? 'Continue your journey.' : 'Create your place here.'}</h2><p className="muted">{mode === 'login' ? 'Sign in to pick up where you left off.' : 'Start building meaningful learning connections.'}</p><form onSubmit={submit}>{mode === 'signup' && <><label>Username<input required name="username" value={form.username} onChange={change} placeholder="Choose a username" /></label><label>I am joining as<select name="role" value={form.role} onChange={change}><option value="student">Student</option><option value="teacher">Teacher</option><option value="school">School / Institution</option></select></label></>}<label>Email address<input required type="email" name="email" value={form.email} onChange={change} placeholder="you@example.com" /></label><label>Password<input required minLength="6" type="password" name="password" value={form.password} onChange={change} placeholder="At least 6 characters" /></label><Button disabled={busy} type="submit">{busy ? 'Please wait…' : mode === 'login' ? <>Sign in <b>{icons.arrow}</b></> : 'Create account'}</Button></form><p className="switcher">{mode === 'login' ? 'New to EduConnect?' : 'Already have an account?'} <button onClick={() => setMode(mode === 'login' ? 'signup' : 'login')}>{mode === 'login' ? 'Create an account' : 'Sign in'}</button></p></div></section></main>;
}

function Sidebar({ page, setPage, role, onLogout, profile }) {
  const nav = [{id:'overview',label:'Overview',icon:'home'},{id:'feed',label:'Community feed',icon:'feed'},{id:'courses',label:'Courses',icon:'courses'},{id:'notes',label:'Learning notes',icon:'notes'},{id:'people',label:'People',icon:'people'},{id:'messages',label:'Messages',icon:'messages'}];
  if (role === 'student') nav.push({id:'admission',label:'Admissions',icon:'applications'});
  if (role === 'teacher') nav.push({id:'applications',label:'School applications',icon:'applications'});
  if (role === 'school') nav.push({id:'applications',label:'Applications',icon:'applications'});
  if (role === 'admin') nav.push({id:'admin',label:'Community controls',icon:'admin'});
  return <aside className="sidebar"><Logo/><nav>{nav.map(x => <button key={x.id} className={page === x.id ? 'active' : ''} onClick={() => setPage(x.id)}><i>{icons[x.icon]}</i>{x.label}</button>)}</nav><div className="sidebar-bottom"><button className={page === 'profile' ? 'active' : ''} onClick={() => setPage('profile')}><i>{icons.profile}</i>My profile</button><button onClick={onLogout}><i>{icons.logout}</i>Sign out</button><div className="mini-person"><div>{(profile?.name || profile?.email || 'E')[0].toUpperCase()}</div><span><b>{profile?.name || profile?.email?.split('@')[0] || 'Member'}</b><small>{role}</small></span></div></div></aside>;
}

function Header({ title, subtitle, onNewPost, notifications = 0 }) { return <header className="topbar"><div><h1>{title}</h1><p>{subtitle}</p></div><div className="header-actions"><button className="theme-toggle" onClick={() => window.dispatchEvent(new Event('educonnect:theme'))} title="Toggle day/night theme">◐</button><button className="notification" onClick={() => window.dispatchEvent(new Event('educonnect:notifications'))}>{icons.bell}{notifications > 0 && <sup>{notifications}</sup>}</button>{onNewPost && <Button onClick={onNewPost}><b>+</b> Share an update</Button>}</div></header>; }
function Metric({ label, value, accent }) { return <div className="metric"><span className={`metric-icon ${accent}`}>✦</span><div><b>{value}</b><small>{label}</small></div></div>; }
function Empty({ title, text, action, onAction }) { return <div className="empty"><div>✦</div><h3>{title}</h3><p>{text}</p>{action && <Button onClick={onAction}>{action}</Button>}</div>; }

function Overview({ role, profile, data, setPage, openPost }) { const [title, subtitle] = roleCopy[role]; return <><Header title={`Good to see you${profile?.name ? `, ${profile.name.split(' ')[0]}` : ''}.`} subtitle="Your learning world is ready when you are." onNewPost={openPost} setPage={setPage}/><div className="dashboard"><section className="welcome-card"><span className="eyebrow">{title}</span><h2>{subtitle}</h2><p>Make today count — explore a course, start a conversation, or share something useful with your community.</p><div><Button onClick={() => setPage('courses')}>Explore courses {icons.arrow}</Button><button className="text-button" onClick={() => setPage('feed')}>Visit the feed</button></div><span className="abstract-shape">✦</span></section><section className="metrics">{role === 'student' ? <><Metric value={data.courses?.length || 0} label="Courses available" accent="blue"/><Metric value={data.notes?.length || 0} label="Shared notes" accent="amber"/><Metric value={data.people?.length || 0} label="People to connect" accent="pink"/></> : <><Metric value={data.posts?.length || 0} label="Community updates" accent="blue"/><Metric value={data.people?.length || 0} label="People in network" accent="amber"/><Metric value={data.courses?.length || 0} label="Learning paths" accent="pink"/></>}</section><section className="content-card recent"><div className="section-heading"><div><span className="eyebrow">IN THE COMMUNITY</span><h2>Recent conversations</h2></div><button className="text-button" onClick={() => setPage('feed')}>View all {icons.arrow}</button></div>{data.posts?.length ? data.posts.slice(0,3).map((p,i) => <Post key={i} post={p}/>) : <Empty title="Be the first voice here" text="Share a thought, resource, or milestone with your community." action="Share an update" onAction={openPost}/>}</section></div></> }
function Post({ post, onLike=()=>{}, onComment=async()=>{}, onSave=()=>{}, notify=()=>{} }) { const [commentOpen,setCommentOpen]=useState(false),[comment,setComment]=useState(''); const submit=async e=>{e.preventDefault();if(!comment.trim())return;await onComment(post,comment);setComment('');setCommentOpen(false)}; const share=async()=>{const url=`${location.origin}/post/${post.id}`;try{await navigator.clipboard.writeText(url);notify('Post link copied.','success')}catch{notify('Share link: '+url,'success')}}; return <article className="post"><div className="avatar">{(post.created_by || 'E')[0].toUpperCase()}</div><div className="post-body"><div><b>{post.created_by?.split('@')[0] || 'EduConnect member'}</b><span className="role-chip">{post.role || 'community'}</span></div><h3>{post.title}</h3><p>{post.content}</p>{post.image_url && <img src={post.image_url} alt="Post attachment"/>}{post.video_url && <video controls src={post.video_url}/>}<div className="post-actions"><button className={post.has_liked?'liked':''} onClick={()=>onLike(post)}>♥ <span>{post.likes || 0}</span> Appreciate</button><button onClick={()=>setCommentOpen(!commentOpen)}>◌ <span>{post.comments?.length || 0}</span> Comment</button><button onClick={share}>↗ Share</button><button onClick={()=>onSave(post)}>▱ Save</button></div>{commentOpen&&<form className="comment-form" onSubmit={submit}><input autoFocus value={comment} onChange={e=>setComment(e.target.value)} placeholder="Add a thoughtful comment…"/><Button>Post</Button></form>}{post.comments?.length>0&&<div className="comment-list">{post.comments.slice(-2).map((c,i)=><p key={c.id||i}><b>{c.commented_by?.split('@')[0]}</b> {c.comment}</p>)}</div>}</div></article>; }

function Feed({ posts, token, reload, notify, openPost, notifications }) { async function like(post){try{await api(`/like-post/${post.id}`,{method:'POST',token});reload()}catch(e){notify(e.message,'error')}} async function comment(post,text){try{await api(`/comment-post/${post.id}?comment=${encodeURIComponent(text)}`,{method:'POST',token});reload();notify('Comment added.','success')}catch(e){notify(e.message,'error')}} async function save(post){try{await api(`/save-post/${post.id}`,{method:'POST',token});notify('Post saved to your collection.','success')}catch(e){notify(e.message,'error')}} return <><Header title="Community feed" subtitle="Ideas, milestones and helpful resources from your network." onNewPost={openPost} notifications={notifications}/><main className="page-content"><section className="content-card feed-card"><div className="feed-intro"><span className="eyebrow">YOUR COMMUNITY</span><h2>What’s unfolding today</h2></div>{posts.length ? posts.map((p,i)=><Post key={p.id||i} post={p} onLike={like} onComment={comment} onSave={save} notify={notify}/>):<Empty title="Your feed is ready" text="Follow people and share an update to make this space yours." action="Share an update" onAction={openPost}/>}</section></main></> }

function Courses({ courses, role, token, notify, reload }) { const [creating,setCreating] = useState(false); const [form,setForm] = useState({title:'',description:'',category:''}); async function submit(e){e.preventDefault();try{await api('/create-course',{method:'POST',token,body:form});notify('Course published successfully.','success');setCreating(false);reload();}catch(x){notify(x.message,'error')}} async function enroll(c){if(!c.id)return notify('Course enrollment needs the course ID in the backend response.','error');try{await api(`/enroll-course/${c.id}`,{method:'POST',token});notify('You are enrolled. Happy learning!','success')}catch(x){notify(x.message,'error')}} return <><Header title="Learning library" subtitle="Explore practical learning paths, created by the community." onNewPost={()=>{}}/><main className="page-content"><div className="section-heading"><div><span className="eyebrow">{courses.length} AVAILABLE</span><h2>Find your next direction</h2></div>{(role==='teacher'||role==='school'||role==='admin')&&<Button onClick={()=>setCreating(!creating)}>+ Create course</Button>}</div>{creating&&<form className="inline-form" onSubmit={submit}><input required placeholder="Course title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><input required placeholder="Category" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/><textarea required placeholder="What will learners gain?" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><Button>Publish course</Button></form>}<div className="course-grid">{courses.length?courses.map((c,i)=><article className="course-card" key={i}><span className="course-number">0{i+1}</span><span className="tag">{c.category||'Learning'}</span><h3>{c.title}</h3><p>{c.description}</p><footer><span>By {c.created_by?.split('@')[0]||'EduConnect'}</span><button onClick={()=>enroll(c)}>Explore {icons.arrow}</button></footer></article>):<Empty title="The library is waiting" text="Courses published by teachers and schools will appear here."/>}</div></main></> }

function People({ people, token, notify }) { const [query,setQuery]=useState(''); const [results,setResults]=useState(people); async function search(e){e.preventDefault();if(!query.trim())return setResults(people);try{const d=await api(`/search-users/${encodeURIComponent(query)}`);setResults(d.results||[])}catch(x){notify(x.message,'error')}} async function follow(email){try{await api(`/follow/${encodeURIComponent(email)}`,{method:'POST',token});notify(`You are now following ${email}.`,'success')}catch(x){notify(x.message,'error')}} return <><Header title="Find your people" subtitle="The right conversation can change a whole learning journey." onNewPost={()=>{}}/><main className="page-content"><form className="search-bar" onSubmit={search}><span>{icons.search}</span><input placeholder="Search by name, email or interest" value={query} onChange={e=>setQuery(e.target.value)}/><Button>Search</Button></form><div className="people-grid">{results.map((p,i)=><article className="person-card" key={p.email||i}><div className="avatar large">{(p.name||p.email||'E')[0].toUpperCase()}</div><span className="role-chip">{p.role}</span><h3>{p.name||p.email?.split('@')[0]}</h3><p>{p.bio||'Here to learn, contribute, and connect.'}</p><Button className="outline" onClick={()=>follow(p.email)}>Follow</Button></article>)}{!results.length&&<Empty title="No people found" text="Try a different name or keyword."/>}</div></main></> }

function Notes({ notes, role, token, notify, reload }) { const [open,setOpen]=useState(false), [form,setForm]=useState({title:'',description:'',file_url:''}); async function submit(e){e.preventDefault();try{await api('/upload-note',{method:'POST',token,body:form});notify('Learning note shared.','success');setOpen(false);reload()}catch(x){notify(x.message,'error')}} return <><Header title="Learning notes" subtitle="Useful resources, thoughtfully collected in one place." onNewPost={()=>{}}/><main className="page-content"><div className="section-heading"><div><span className="eyebrow">COMMUNITY RESOURCES</span><h2>Learn from each other</h2></div>{role!=='student'&&<Button onClick={()=>setOpen(!open)}>+ Share a note</Button>}</div>{open&&<form className="inline-form" onSubmit={submit}><input required placeholder="Resource title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><input required type="url" placeholder="Resource URL" value={form.file_url} onChange={e=>setForm({...form,file_url:e.target.value})}/><textarea required placeholder="Describe this resource" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><Button>Share resource</Button></form>}<div className="notes-list">{notes.length?notes.map((n,i)=><article className="note" key={i}><span className="note-icon">↗</span><div><h3>{n.title}</h3><p>{n.description}</p><small>Shared by {n.uploaded_by?.split('@')[0]||'community member'}</small></div><a href={n.file_url} target="_blank" rel="noreferrer">Open resource {icons.arrow}</a></article>):<Empty title="No notes yet" text="Helpful notes and resources will appear here."/>}</div></main></> }

function Profile({ profile, token, notify, onUpdated }) { const [form,setForm]=useState({name:profile?.name||'',bio:profile?.bio||'',phone:profile?.phone||''}); useEffect(()=>setForm({name:profile?.name||'',bio:profile?.bio||'',phone:profile?.phone||''}),[profile]); async function submit(e){e.preventDefault();try{await api('/update-profile',{method:'PUT',token,body:form});onUpdated();notify('Your profile has been updated.','success')}catch(x){notify(x.message,'error')}} return <><Header title="Your profile" subtitle="The details that help your community know you better." onNewPost={()=>{}}/><main className="page-content"><section className="profile-layout"><div className="profile-identity"><div className="avatar profile-avatar">{(profile?.name||profile?.email||'E')[0].toUpperCase()}</div><span className="role-chip">{profile?.role}</span><h2>{profile?.name||profile?.email?.split('@')[0]}</h2><p>{profile?.email}</p><p className="bio-preview">{profile?.bio||'Add a bio to tell your learning community a little about yourself.'}</p></div><form className="profile-form" onSubmit={submit}><span className="eyebrow">PERSONAL DETAILS</span><h2>Make it yours</h2><label>Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Your name"/></label><label>Bio<textarea required value={form.bio} onChange={e=>setForm({...form,bio:e.target.value})} placeholder="What are you learning or teaching?"/></label><label>Phone<input required value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="Your contact number"/></label><Button>Save changes {icons.check}</Button></form></section></main></> }

function Applications({ role, applications, token, notify, reload }) { const [form,setForm]=useState({school_email:'',full_name:'',age:'',class_name:'',parent_email:'',parent_contact:''}); const [teacher,setTeacher]=useState({school_email:'',full_name:'',subject:'',experience:'',qualifications:'',area_of_interest:'',skills:'',certificates_url:'',cv_url:''}); const submit=async(e,type)=>{e.preventDefault();try{await api(type==='admission'?'/apply-admission':'/apply-school',{method:'POST',token,body:type==='admission'?{...form,age:Number(form.age)}:teacher});notify('Application submitted successfully.','success');reload()}catch(x){notify(x.message,'error')}}; async function update(id,status){try{await api(`/school/admission/${status}/${id}`,{method:'POST',token});notify(`Application ${status}.`,'success');reload()}catch(x){notify(x.message,'error')}} if(role==='student')return <><Header title="Admissions" subtitle="Take the next confident step in your education." onNewPost={()=>{}}/><main className="page-content"><form className="application-form" onSubmit={e=>submit(e,'admission')}><span className="eyebrow">STUDENT APPLICATION</span><h2>Apply to a school</h2>{[['school_email','School email','email'],['full_name','Full name','text'],['age','Age','number'],['class_name','Class / grade','text'],['parent_email','Parent email','email'],['parent_contact','Parent contact','text']].map(([k,l,t])=><label key={k}>{l}<input required type={t} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<Button>Submit application</Button></form></main></>;
if(role==='teacher')return <><Header title="School applications" subtitle="Find schools where your expertise can make a difference." onNewPost={()=>{}}/><main className="page-content"><form className="application-form" onSubmit={e=>submit(e,'teacher')}><span className="eyebrow">TEACHER APPLICATION</span><h2>Apply to a school</h2>{[['school_email','School email'],['full_name','Full name'],['subject','Subject'],['experience','Experience'],['qualifications','Qualifications'],['area_of_interest','Area of interest'],['skills','Skills'],['certificates_url','Certificates URL'],['cv_url','CV URL']].map(([k,l])=><label key={k}>{l}<input required={k!=='certificates_url'} value={teacher[k]} onChange={e=>setTeacher({...teacher,[k]:e.target.value})}/></label>)}<Button>Submit application</Button></form></main></>;
return <><Header title="Applications" subtitle="Review and respond to prospective members of your school." onNewPost={()=>{}}/><main className="page-content"><section className="content-card"><div className="section-heading"><div><span className="eyebrow">INCOMING</span><h2>Admissions to review</h2></div></div>{applications.length?applications.map((a,i)=><article className="application-row" key={a._id||i}><div><span className="role-chip">{a.status}</span><h3>{a.full_name}</h3><p>{a.student_email} · Class {a.class_name}</p></div>{a._id&&a.status==='pending'&&<div><Button onClick={()=>update(a._id,'approve')}>Approve</Button><Button className="outline danger" onClick={()=>update(a._id,'reject')}>Decline</Button></div>}</article>):<Empty title="Nothing to review" text="New applications will appear here."/>}</section></main></> }

function Admin({ people, token, notify, reload }) { async function action(email,type){try{await api(`/${type}-user/${encodeURIComponent(email)}`,{method:'POST',token});notify(`User ${type === 'verify' ? 'verified' : 'banned'} successfully.`,'success');reload()}catch(x){notify(x.message,'error')}} return <><Header title="Community controls" subtitle="A safer, more trusted community starts with thoughtful stewardship." onNewPost={()=>{}}/><main className="page-content"><section className="content-card"><div className="section-heading"><div><span className="eyebrow">MEMBER DIRECTORY</span><h2>Manage community access</h2></div></div>{people.map((p,i)=><article className="application-row" key={p.email||i}><div><h3>{p.name||p.email?.split('@')[0]} <span className="role-chip">{p.role}</span></h3><p>{p.email}</p></div><div><Button onClick={()=>action(p.email,'verify')}>Verify</Button><Button className="outline danger" onClick={()=>action(p.email,'ban')}>Ban</Button></div></article>)}</section></main></> }
function Messages({ messages, people, token, notify, reload }) { const [recipient,setRecipient]=useState(''),[text,setText]=useState(''); async function send(e){e.preventDefault();try{await api('/send-message',{method:'POST',token,body:{receiver_email:recipient,message:text}});setText('');notify('Message delivered.','success');reload()}catch(x){notify(x.message,'error')}} return <><Header title="Messages" subtitle="Live conversations that keep learning moving."/><main className="page-content"><section className="chat-layout"><form className="message-composer" onSubmit={send}><span className="eyebrow">NEW MESSAGE</span><h2>Start a conversation</h2><select required value={recipient} onChange={e=>setRecipient(e.target.value)}><option value="">Choose a member</option>{people.map(p=><option key={p.email} value={p.email}>{p.name||p.email} · {p.role}</option>)}</select><textarea required value={text} onChange={e=>setText(e.target.value)} placeholder="Write a message…"/><Button>Send message {icons.arrow}</Button></form><section className="content-card">{messages.length?messages.map((m,i)=><article className="message-row" key={i}><div className="avatar">{m.sender?.[0]?.toUpperCase()}</div><div><b>{m.sender}</b><p>{m.message}</p></div></article>):<Empty title="Your inbox is quiet" text="Start a conversation and build your learning network."/>}</section></section></main></> }
function PostModal({ token, close, notify, reload }) { const [form,setForm]=useState({title:'',content:'',image_url:'',video_url:'',audience:'community'}),[file,setFile]=useState(null),[busy,setBusy]=useState(false); async function submit(e){e.preventDefault();setBusy(true);try{let image_url=form.image_url;if(file){const fd=new FormData();fd.append('file',file);const uploaded=await api('/upload-media',{method:'POST',token,formData:fd});image_url=uploaded.media_url}await api('/create-post',{method:'POST',token,body:{...form,image_url}});notify('Your update is live.','success');close();reload()}catch(x){notify(x.message,'error')}finally{setBusy(false)}}return <div className="modal-backdrop"><form className="modal" onSubmit={submit}><button className="close" type="button" onClick={close}>×</button><span className="eyebrow">SHARE WITH YOUR COMMUNITY</span><h2>What’s worth passing on?</h2><input required placeholder="A clear, helpful title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><textarea required placeholder="Write your update…" value={form.content} onChange={e=>setForm({...form,content:e.target.value})}/><label className="file-input">Attach image or video<input type="file" accept="image/*,video/*" onChange={e=>setFile(e.target.files?.[0])}/></label><input type="url" placeholder="Image / video URL (optional)" value={form.image_url} onChange={e=>setForm({...form,image_url:e.target.value})}/><select value={form.audience} onChange={e=>setForm({...form,audience:e.target.value})}><option value="community">Everyone in EduConnect</option><option value="students">Students only</option><option value="teachers">Teachers only</option><option value="schools">Schools only</option></select><Button disabled={busy}>{busy?'Uploading…':'Publish update '+icons.arrow}</Button></form></div> }

function NotificationDrawer({items,close}){return <div className="notification-drawer"><div><b>Notifications</b><button onClick={close}>×</button></div>{items.length?items.map((n,i)=><p key={i}>● {n}</p>):<p className="muted">You’re all caught up.</p>}</div>}
function App(){ const [token,setToken]=useState(()=>localStorage.getItem('educonnect_token')); const [page,setPage]=useState('overview'); const [profile,setProfile]=useState(null); const [data,setData]=useState({posts:[],courses:[],notes:[],people:[],messages:[],applications:[],notifications:[]}); const [toast,setToast]=useState(null); const [postOpen,setPostOpen]=useState(false); const [drawer,setDrawer]=useState(false); const [theme,setTheme]=useState(()=>localStorage.getItem('educonnect_theme')||'light'); const role=useMemo(()=>decodeToken(token||'').role,[token]); const notify=(message,type='success')=>setToast({message,type}); const logout=()=>{localStorage.removeItem('educonnect_token');setToken(null);setProfile(null);setPage('overview')}; const onAuth=t=>{localStorage.setItem('educonnect_token',t);setToken(t);setPage('overview');notify('Welcome to EduConnect.','success')};
const load=async()=>{if(!token)return;try{const calls=[api('/my-profile',{token}),api('/all-posts',{token}),api('/all-courses'),api('/all-notes'),api('/all-users'),api('/my-messages',{token}),api('/notifications',{token})];if(role==='school')calls.push(api('/school/admissions',{token}));if(role==='teacher')calls.push(api('/teacher-applications',{token}));const r=await Promise.all(calls);setProfile(r[0].profile);setData({posts:r[1].posts||[],courses:r[2].courses||[],notes:r[3].notes||[],people:r[4].users||[],messages:r[5].messages||[],notifications:r[6].notifications||[],applications:r[7]?.applications||[]});api('/set-online',{method:'POST',token}).catch(()=>{})}catch(e){if(e.status===401){logout();notify('Your session expired. Please sign in again.','error')}else notify(e.message,'error')}};
useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('educonnect_theme',theme)},[theme]);useEffect(()=>{const toggle=()=>setTheme(x=>x==='light'?'dark':'light'),open=()=>setDrawer(true);window.addEventListener('educonnect:theme',toggle);window.addEventListener('educonnect:notifications',open);return()=>{window.removeEventListener('educonnect:theme',toggle);window.removeEventListener('educonnect:notifications',open)}},[]);useEffect(()=>{load()},[token]);useEffect(()=>{if(!token)return;const socket=new WebSocket(API_URL.replace(/^http/,'ws')+`/ws?token=${encodeURIComponent(token)}`);socket.onmessage=e=>{const event=JSON.parse(e.data);if(event.event==='message'){setData(d=>({...d,messages:[...d.messages,event.payload]}));notify('New message received.','success')}if(event.event==='notification'){setData(d=>({...d,notifications:[event.payload.message,...d.notifications]}));notify(event.payload.message,'success')}};return()=>socket.close()},[token]);if(!token)return <>{toast&&<Toast {...toast} onClose={()=>setToast(null)}/>}<Auth onAuth={onAuth} notify={notify}/></>;
let view;const common={token,notify,reload:load,notifications:data.notifications.length};if(page==='overview')view=<Overview role={role} profile={profile} data={data} setPage={setPage} openPost={()=>setPostOpen(true)}/>;else if(page==='feed')view=<Feed posts={data.posts} {...common} openPost={()=>setPostOpen(true)}/>;else if(page==='courses')view=<Courses courses={data.courses} role={role} {...common}/>;else if(page==='notes')view=<Notes notes={data.notes} role={role} {...common}/>;else if(page==='people')view=<People people={data.people} {...common}/>;else if(page==='messages')view=<Messages messages={data.messages} people={data.people} {...common}/>;else if(page==='profile')view=<Profile profile={profile} {...common} onUpdated={load}/>;else if(page==='applications'||page==='admission')view=<Applications role={role} applications={data.applications} {...common}/>;else view=<Admin people={data.people} {...common}/>;return <div className="app-shell"><Sidebar page={page} setPage={setPage} role={role} onLogout={logout} profile={profile}/><div className="main-area">{view}</div>{postOpen&&<PostModal {...common} close={()=>setPostOpen(false)}/>} {drawer&&<NotificationDrawer items={data.notifications} close={()=>setDrawer(false)}/>} {toast&&<Toast {...toast} onClose={()=>setToast(null)}/>}</div> }
export default App;
